name: Build Beta

on:
  workflow_dispatch:  # 改为手动触发
  # push:
  #   branches:
  #     - beta

jobs:
  Android:
    name: Android
    runs-on: ubuntu-latest
    steps:
      - name: Check out git repository
        uses: actions/checkout@v4

      - name: Setup Env
        uses: ./.github/actions/setup

      - name: Build Packages
        shell: bash
        run: |
          cd android
          # 构建 Debug 版本，无需签名
          ./gradlew assembleDebug

      # Push tag to GitHub if package.json version's tag is not tagged
      - name: Get package version
        run: |
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV

      - name: Generate file MD5
        run: |
          cd android/app/build/outputs/apk/debug
          md5sum *.apk

      - name: Upload Artifact
        uses: ./.github/actions/upload-artifact
        env:
          PACKAGE_VERSION: ${{ env.PACKAGE_VERSION }}
